version: "3.7"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    links:
      - postgres
      - redis

  postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: "gin-admin"
      POSTGRES_PASSWORD: 123456
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    volumes:
      - rddata:/data

volumes:
  pgdata:
  rddata:
