---
# 菜单配置初始化(服务启动时会进行数据检查，如果存在则不再初始化)
- name: 首页
  icon: dashboard
  router: "/dashboard"
  sequence: 1
- name: DEMO
  icon: tag
  router: "/example/demo"
  sequence: 2
- name: 系统管理
  icon: setting
  sequence: 3
  children:
    - name: 菜单管理
      icon: solution
      router: "/system/menu"
      sequence: 1
    - name: 角色管理
      icon: audit
      router: "/system/role"
      sequence: 2
    - name: 用户管理
      icon: user
      router: "/system/user"
      sequence: 3
    - name: 路由资源管理
      icon: routerResource
      router: "/system/routerResource"
      sequence: 4