definitions:
  schema.Demo:
    properties:
      code:
        description: 编号
        type: string
      created_at:
        description: 创建时间
        type: string
      creator:
        description: 创建者
        type: string
      id:
        description: 唯一标识
        type: string
      memo:
        description: 备注
        type: string
      name:
        description: 名称
        type: string
      status:
        description: 状态(1:启用 2:停用)
        type: integer
      updated_at:
        description: 更新时间
        type: string
    required:
    - code
    - name
    - status
    type: object
  schema.ErrorItem:
    properties:
      code:
        description: 错误码
        type: integer
      message:
        description: 错误信息
        type: string
    type: object
  schema.ErrorResult:
    properties:
      error:
        $ref: '#/definitions/schema.ErrorItem'
        description: 错误项
    type: object
  schema.IDResult:
    properties:
      id:
        type: string
    type: object
  schema.ListResult:
    properties:
      list: {}
      pagination:
        $ref: '#/definitions/schema.PaginationResult'
    type: object
  schema.LoginCaptcha:
    properties:
      captchaId:
        description: 验证码ID
        type: string
    type: object
  schema.LoginParam:
    properties:
      captchaCode:
        description: 验证码
        type: string
      captchaId:
        description: 验证码ID
        type: string
      password:
        description: 密码(md5加密)
        type: string
      userName:
        description: 用户名
        type: string
    required:
    - captchaCode
    - captchaId
    - password
    - userName
    type: object
  schema.LoginTokenInfo:
    properties:
      accessToken:
        description: 访问令牌
        type: string
      expiresAt:
        description: 令牌到期时间戳
        type: integer
      tokenType:
        description: 令牌类型
        type: string
    type: object
  schema.PaginationResult:
    properties:
      current:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
  schema.StatusResult:
    properties:
      status:
        description: 状态(OK)
        type: string
    type: object
  schema.UpdatePasswordParam:
    properties:
      newPassword:
        description: 新密码(md5加密)
        type: string
      oldPassword:
        description: 旧密码(md5加密)
        type: string
    required:
    - newPassword
    - oldPassword
    type: object
  schema.User:
    properties:
      avatar:
        description: 头像
        type: string
      createdAt:
        description: 创建时间
        type: string
      creator:
        description: 创建者
        type: string
      email:
        description: 邮箱
        type: string
      id:
        description: 唯一标识
        type: string
      password:
        description: 密码
        type: string
      phone:
        description: 手机号
        type: string
      realName:
        description: 真实姓名
        type: string
      status:
        description: 用户状态(1:启用 2:停用)
        type: integer
      userName:
        description: 用户名
        type: string
    required:
    - avatar
    - realName
    - status
    - userName
    type: object
  schema.UserLoginInfo:
    properties:
      realName:
        description: 真实姓名
        type: string
      userId:
        description: 用户ID
        type: string
      userName:
        description: 用户名
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/management/demos:
    get:
      parameters:
      - default: 1
        description: 分页索引
        in: query
        name: current
        required: true
        type: integer
      - default: 10
        description: 分页大小
        in: query
        name: pageSize
        required: true
        type: integer
      - description: 查询值
        in: query
        name: queryValue
        type: string
      responses:
        "200":
          description: 查询结果
          schema:
            allOf:
            - $ref: '#/definitions/schema.ListResult'
            - properties:
                list:
                  items:
                    $ref: '#/definitions/schema.Demo'
                  type: array
              type: object
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      security:
      - ApiKeyAuth: []
      summary: 查询数据
      tags:
      - Demo
    post:
      parameters:
      - description: 创建数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.Demo'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.IDResult'
        "400":
          description: '{error:{code:0,message:无效的请求参数}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      security:
      - ApiKeyAuth: []
      summary: 创建数据
      tags:
      - Demo
  /api/v1/management/demos/{id}:
    delete:
      parameters:
      - description: 唯一标识
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{status:OK}'
          schema:
            $ref: '#/definitions/schema.StatusResult'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      security:
      - ApiKeyAuth: []
      summary: 删除数据
      tags:
      - Demo
    get:
      parameters:
      - description: 唯一标识
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.Demo'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "404":
          description: '{error:{code:0,message:资源不存在}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      security:
      - ApiKeyAuth: []
      summary: 查询指定数据
      tags:
      - Demo
    put:
      parameters:
      - description: 唯一标识
        in: path
        name: id
        required: true
        type: string
      - description: 更新数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.Demo'
      responses:
        "200":
          description: '{status:OK}'
          schema:
            $ref: '#/definitions/schema.StatusResult'
        "400":
          description: '{error:{code:0,message:无效的请求参数}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      security:
      - ApiKeyAuth: []
      summary: 更新数据
      tags:
      - Demo
  /api/v1/management/demos/{id}/disable:
    patch:
      parameters:
      - description: 唯一标识
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{status:OK}'
          schema:
            $ref: '#/definitions/schema.StatusResult'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      security:
      - ApiKeyAuth: []
      summary: 禁用数据
      tags:
      - Demo
  /api/v1/management/demos/{id}/enable:
    patch:
      parameters:
      - description: 唯一标识
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{status:OK}'
          schema:
            $ref: '#/definitions/schema.StatusResult'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      security:
      - ApiKeyAuth: []
      summary: 启用数据
      tags:
      - Demo
  /api/v1/management/users:
    get:
      parameters:
      - default: 1
        description: 分页索引
        in: query
        name: current
        required: true
        type: integer
      - default: 10
        description: 分页大小
        in: query
        name: pageSize
        required: true
        type: integer
      - description: 查询值
        in: query
        name: queryValue
        type: string
      - description: 状态(1:启用 2:停用)
        in: query
        name: status
        type: integer
      responses:
        "200":
          description: 查询结果
          schema:
            allOf:
            - $ref: '#/definitions/schema.ListResult'
            - properties:
                list:
                  items:
                    items:
                      $ref: '#/definitions/schema.User'
                    type: array
                  type: array
              type: object
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      security:
      - ApiKeyAuth: []
      summary: 查询数据
      tags:
      - 用户管理
    post:
      parameters:
      - description: 创建数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.User'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.IDResult'
        "400":
          description: '{error:{code:0,message:无效的请求参数}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      security:
      - ApiKeyAuth: []
      summary: 创建数据
      tags:
      - 用户管理
  /api/v1/management/users/{id}:
    delete:
      parameters:
      - description: 唯一标识
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{status:OK}'
          schema:
            $ref: '#/definitions/schema.StatusResult'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      security:
      - ApiKeyAuth: []
      summary: 删除数据
      tags:
      - 用户管理
    get:
      parameters:
      - description: 唯一标识
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.User'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "404":
          description: '{error:{code:0,message:资源不存在}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      security:
      - ApiKeyAuth: []
      summary: 查询指定数据
      tags:
      - 用户管理
    put:
      parameters:
      - description: 唯一标识
        in: path
        name: id
        required: true
        type: string
      - description: 更新数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.User'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.User'
        "400":
          description: '{error:{code:0,message:无效的请求参数}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      security:
      - ApiKeyAuth: []
      summary: 更新数据
      tags:
      - 用户管理
  /api/v1/management/users/{id}/disable:
    patch:
      parameters:
      - description: 唯一标识
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{status:OK}'
          schema:
            $ref: '#/definitions/schema.StatusResult'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      security:
      - ApiKeyAuth: []
      summary: 禁用数据
      tags:
      - 用户管理
  /api/v1/management/users/{id}/enable:
    patch:
      parameters:
      - description: 唯一标识
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{status:OK}'
          schema:
            $ref: '#/definitions/schema.StatusResult'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      security:
      - ApiKeyAuth: []
      summary: 启用数据
      tags:
      - 用户管理
  /api/v1/pub/current/password:
    put:
      parameters:
      - description: 请求参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.UpdatePasswordParam'
      responses:
        "200":
          description: '{status:OK}'
          schema:
            $ref: '#/definitions/schema.StatusResult'
        "400":
          description: '{error:{code:0,message:无效的请求参数}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      security:
      - ApiKeyAuth: []
      summary: 更新个人密码
      tags:
      - 登录管理
  /api/v1/pub/current/user:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.UserLoginInfo'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      security:
      - ApiKeyAuth: []
      summary: 获取当前用户信息
      tags:
      - 登录管理
  /api/v1/pub/login:
    post:
      parameters:
      - description: 请求参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.LoginParam'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.LoginTokenInfo'
        "400":
          description: '{error:{code:0,message:无效的请求参数}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      summary: 用户登录
      tags:
      - 登录管理
  /api/v1/pub/login/captcha:
    get:
      parameters:
      - description: 验证码ID
        in: query
        name: id
        required: true
        type: string
      - description: 重新加载
        in: query
        name: reload
        type: string
      produces:
      - image/png
      responses:
        "200":
          description: 图形验证码
        "400":
          description: '{error:{code:0,message:无效的请求参数}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      summary: 响应图形验证码
      tags:
      - 登录管理
  /api/v1/pub/login/captchaid:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.LoginCaptcha'
      summary: 获取验证码信息
      tags:
      - 登录管理
  /api/v1/pub/login/exit:
    post:
      responses:
        "200":
          description: '{status:OK}'
          schema:
            $ref: '#/definitions/schema.StatusResult'
      summary: 用户登出
      tags:
      - 登录管理
  /api/v1/pub/refresh-token:
    post:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.LoginTokenInfo'
        "401":
          description: '{error:{code:0,message:未授权}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.ErrorResult'
      security:
      - ApiKeyAuth: []
      summary: 刷新令牌
      tags:
      - 登录管理
swagger: "2.0"
